language: node_js
node_js:
- 0.10
before_install:
- git checkout -B gh-pages
- npm install
before_script:
- npm install bower -g
after_success:
- bower install
- git merge master
- git push github gh-pages