language: node_js
node_js:
- 0.10
before_install:
- git pull github gh-pages
- git checkout gh-pages
- sudo npm install
before_script:
- npm install bower -g
after_success:
- bower install
- git merge master